---

# Do some pre-test setup
- hosts: all
  tasks:

    - name: install epel
      become: yes
      yum:
        name: epel-release
        state: present

    - name: install nginx
      become: yes
      yum:
        name: nginx
        state: present

    - name: start nginx
      become: yes
      service:
        enabled: yes
        name: nginx
        state: started

    - name: ensure /var/log/nginx is accessible
      become: yes
      file:
        path: /var/log/nginx
        mode: "g+rx"


# Now test the fluentd role deployment
- hosts: all
  roles:
    - role: ansible-role-fluentd
      fluentd_groups: nginx
      fluentd_plugins:
        - fluent-plugin-slack
      fluentd_env:
        SLACK_TOKEN: xoxp-SECRET-SLACK-TOKEN

  tasks:

    - name: copy nginx fluentd config
      become: yes
      copy:
        src: tests/fluentd-conf/fluentd-nginx.conf
        dest: /etc/td-agent/conf.d/nginx.conf
      notify:
        - restart fluentd
