---
# tasks file for roles/fluentd

- name: fluentd | yum repo
  become: yes
  copy:
    src: yum-reposd-fluentd.repo
    dest: /etc/yum.repos.d/fluentd.repo

- name: fluentd | install
  become: yes
  yum:
    name: "{{ fluentd_name }}"
    state: present
  notify:
    - restart fluentd

- name: fluentd | configuration directory
  become: yes
  file:
    path: /etc/{{ fluentd_name }}/conf.d
    state: directory

- name: fluentd | main configuration
  become: yes
  copy:
    src: fluentd.conf
    dest: /etc/{{ fluentd_name }}/{{ fluentd_name }}.conf
  notify:
    - restart fluentd

- name: fluentd | start service
  become: yes
  service:
    enabled: yes
    name: "{{ fluentd_name }}"
    state: started

# TODO: service enabled=yes doesn't work for td-agent for unknown reasons
# This is a workaround to manually enable the service
- name: fluentd | workaround service enable bug
  become: yes
  file:
    dest: /etc/systemd/system/multi-user.target.wants/td-agent.service
    src: /usr/lib/systemd/system/td-agent.service
    state: link
